version: '3.8'
services:
  development:
    build:
      context: ./
      dockerfile: development/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - database

  scrapper:
    build:
      context: ./
      dockerfile: ./.devcontainer/scrapper/Dockerfile
    volumes:
      - ../..:workspaces:cached
    command: sleep infinity
    depends_on:
      - database

  database:
    build:
      context: ./.devcontainer/database/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"