version: '3.8'
services:
  webscrapper:
    build:
      context: ./
      dockerfile: python/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - mysql
  
  mysql:
    build:
      context: ./.devcontainer/mysql/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"