name: GdCPR
services:
  ################################################################
  #################### endi-scrapper #############################
  endi-scrapper:
    container_name: endi-scrapper
    build:
      context: ./
      dockerfile: scrapper/endi-scrapper/Dockerfile
    volumes:
      - ../..:/workspaces:cached
  ################################################################
  ########################## dev #################################
  development:
    container_name: development
    build:
      context: ./
      dockerfile: development/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - endi-scrapper